#! /bin/sh

# Arg1 should specify a week in the form YYYY-WW, where weeks are numbered 1-52
# Arg2 should be 
#   'segment' - ?
#   'warc' - raw response data
#   'wat' - metadata extracts
#   'wet' - text extracts
# Arg3 should specify an integer line number

pathdir="crawl-data/CC-MAIN-$1"
pathfile="$2.paths"
snip=`sed "$3!d;q" "$pathdir/$pathfile"`
echo "$snip"