#! /bin/sh

# Arg1 should specify a week in the form YYYY-WW, where weeks are numbered 1-52
# Arg2 should be 
#   'segment' - ?
#   'warc' - raw response data
#   'wat' - metadata extracts
#   'wet' - text extracts

pathdir="crawl-data/CC-MAIN-$1"
pathfile="$2.paths.gz"
mkdir -p "$pathdir"
curl "https://commoncrawl.s3.amazonaws.com/$pathdir/$pathfile" >"$pathdir/$pathfile"
cp "$pathdir/$pathfile" "$pathdir/$pathfile.BAK"
gunzip -d "$pathdir/$pathfile"
mv "$pathdir/$pathfile.BAK" "$pathdir/$pathfile"
